import{a as v,S as E,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&c(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const P="53393760-f5a058fb9e0a87143d2aaec84",$="https://pixabay.com/api/",B=15;async function y(r,o=1){try{return(await v.get($,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:B}})).data}catch(n){throw console.error(n),n}}const f=document.querySelector(".gallery"),p=document.querySelector(".load-more");document.querySelector(".loader");let M=new E(".gallery a");function g(r){const o=r.map(({webformatURL:n,largeImageURL:c,tags:e,likes:t,views:s,comments:b,downloads:q})=>`
      <li class="gallery-item">
        <a href="${c}" class="gallery-link">
          <img src="${n}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><span class="item-descr-item">Likes:</span> ${t}</p>
          <p><span class="item-descr-item">Views:</span> ${s}</p>
          <p><span class="item-descr-item">Comments:</span> ${b}</p>
          <p><span class="item-descr-item">Downloads:</span> ${q}</p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",o),M.refresh()}function A(){f.innerHTML=""}function h(){document.body.classList.add("loading")}function l(){document.body.classList.remove("loading")}function L(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const w=document.querySelector(".form"),O=w.querySelector('input[name="search-text"]'),_=document.querySelector(".load-more"),x=document.querySelector(".gallery");let u="",i=1,m=0;const S=15;w.addEventListener("submit",async r=>{r.preventDefault();const o=O.value.trim();if(!o){a.error({title:"Error",message:"Please enter a search query."});return}A(),d(),u=o,i=1,h();try{const n=await y(u,i);if(m=n.totalHits,n.hits.length===0){a.info({message:"Sorry, there are no images matching your search query. Please try again!"}),l();return}g(n.hits),S<m&&L()}catch{a.error({title:"Error",message:"Something went wrong! Try again later."})}finally{l()}});_.addEventListener("click",async()=>{i+=1,d(),h();try{const r=await y(u,i);if(g(r.hits),H(),i*S>=m){a.info({message:"We're sorry, but you've reached the end of search results."}),d();return}L()}catch{a.error({title:"Error",message:"Something went wrong!"})}finally{l()}});function H(){const r=x.querySelector(".gallery-item");if(!r)return;const{height:o}=r.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
